app = "your-ai-worker-app-name"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8000"
  PYTHONPATH = "/app"

[deploy]
  release_command = "echo 'AI Worker starting...'"

[[statics]]
  guest_path = "/app/temp"
  url_prefix = "/temp/"

[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    port = 8000
    timeout = "5s"